// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgSUVm0ivY_DXttFSZAxD3ZtoyeMbBWtU',
    appId: '1:402945659070:web:af14e88140ed19a2c74eef',
    messagingSenderId: '402945659070',
    projectId: 'myhotel-db',
    authDomain: 'myhotel-db.firebaseapp.com',
    storageBucket: 'myhotel-db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo_FzJHh4F2Kt6Ap5UiZzlnFhtJPGu5So',
    appId: '1:402945659070:android:f297229efacf5415c74eef',
    messagingSenderId: '402945659070',
    projectId: 'myhotel-db',
    storageBucket: 'myhotel-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzGAKM20HSCjekS6KZD69AZ_jxZ60y4TQ',
    appId: '1:402945659070:ios:e687938c41413aacc74eef',
    messagingSenderId: '402945659070',
    projectId: 'myhotel-db',
    storageBucket: 'myhotel-db.appspot.com',
    iosClientId: '402945659070-a0ckd3i1ckj9tq5ktm3r1hpiinej1kor.apps.googleusercontent.com',
    iosBundleId: 'ma.hotem.mimsett',
  );
}
